### ISSUE TITLE
Dependency material-dialogs:0.3.1 is no longer on jCenter

### ISSUE THREAD

**Issue by krt16s** [JohnPersano/CrimeTalk-Reader#1]
For whatever reason com.afollestad:material-dialogs:0.3.1 is no longer available from jCenter, but com.afollestad:material-dialogs:0.3.2 is, so it might be good to upgrade.

**Comment by JohnPersano** [comment]
Krt16s,

Thank you very much for this information. I will update the project's gradle file in the next version.

- John

**Comment by JohnPersano** [comment]
Dependency has been updated.
